# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bovespa_ingestion}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Felipe Seixas", "Rodrigo Fraga"]
  s.date = %q{2011-12-26}
  s.default_executable = %q{carregar_historico}
  s.email = %q{seixasfelipe@gmail.com}
  s.executables = ["carregar_historico"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "archives/SeriesHistoricas_Layout.pdf",
    "bin/carregar_historico",
    "config/environment.rb",
    "db/config.yml",
    "db/migrate/20111221001450_create_historico.rb",
    "db/migrate/20111222192119_create_ativos.rb",
    "db/migrate/20111223004105_change_ativos.rb",
    "db/migrate/20111223023840_add_quantidade_ativos_to_historico_ativos.rb",
    "db/migrate/20111223131703_add_prazo_termo_to_ativo.rb",
    "db/migrate/20111223213342_alter_reference_historico_ativo.rb",
    "db/migrate/20111223214919_remove_data_importacao.rb",
    "db/schema.rb",
    "lib/historico_ativos.rb",
    "lib/historico_ativos/ativo.rb",
    "lib/historico_ativos/carrega_historico.rb",
    "lib/historico_ativos/header.rb",
    "lib/historico_ativos/historico.rb",
    "lib/historico_ativos/parser_ativo.rb",
    "lib/historico_ativos/parser_header.rb",
    "lib/historico_ativos/parser_trailer.rb",
    "lib/historico_ativos/trailer.rb",
    "sample/DemoCotacoesHistoricas12022003.txt",
    "sample/sample_cota_hist_2003.txt",
    "spec/historico_ativos/ativo_spec.rb",
    "spec/historico_ativos/carrega_historico_spec.rb",
    "spec/historico_ativos/historico_spec.rb",
    "spec/historico_ativos/parser_ativo_spec.rb",
    "spec/historico_ativos/parser_header_spec.rb",
    "spec/historico_ativos/parser_trailer_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/seixasfelipe/bovespa-ingestion}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{An importer of historical quotations from BM&F Bovespa}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 3"])
      s.add_runtime_dependency(%q<standalone_migrations>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 3"])
      s.add_dependency(%q<standalone_migrations>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 3"])
    s.add_dependency(%q<standalone_migrations>, [">= 0"])
  end
end

